### ISSUE TITLE
Maven Dependency Problem - Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100

### ISSUE THREAD

**Issue by dtredinnick13** [TIBCOSoftware/bw6-plugin-maven#184]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version:2.0.0

Maven version:3.5.2

Product :  TIBCO Businessworks Container edition

Product version: 2.4

Component: Either of Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Download and unzip the maven 2.0.0 installer
2 .Run the install.sh script
3. When I installed the plugin I specified /opt/tibco/bwce as the tibco home. This resulted with the plugin being installed at /opt/tibco/bwce/bwce/2.4 as shown:
    dtredinnick@ubuntu:/opt/tibco/bwce/bwce/2.4$ ls
    bin config doc docker ext maven p2repos samples scripts system
4. When I generate the POM, I get the following error:
    Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 pom.xml /GDay.module line 14 Maven Dependency Problem

If I look in the GDay.module/pom.xml file, I see the following:
<dependencies>
    <dependency>
      <groupId>com.tibco.plugins</groupId>
      <artifactId>com.tibco.bw.palette.shared</artifactId>
      <version>6.1.100</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

**Additional environment details if any:**
Running on Ubuntu 18.04 LTS

**Describe the results you received:**
Maven Dependency Problem

**Describe the results you expected:**
Clean POM file generation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by dtredinnick13** [comment]
It looks like this form strips out XML tags when it gets pasted in. Here is the pom file with the issue. 
[pom.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2334389/pom.zip)

**Comment by SujataDarekar** [comment]
@dtredinnick13 
           Could you please check artifact com.tibco.bw.palette.shared is present in .m2 repository(.m2\repository\com\tibco\plugins) or not?
          This issue occurs when com.tibco.bw.palette.shared artifact is not present in .m2 repository. So if it is not present in .m2 repository that means maven plugin is not installed properly and you will need to install it again.
         Also please provide the list of jars present at your path opt/tibco/bwce/bwce/2.4/maven/plugins/bw6-maven-plugin

**Comment by dtredinnick13** [comment]
@SujataDarekar 
Thanks for the quick response.  If I look in the .m2 repository, I do see the artifact:
        dtredinnick@ubuntu:~/.m2/repository/com/tibco/plugins$ ls
        bw6-maven-plugin  com.tibco.bw.palette.shared
The directory opt/tibco/bwce/bwce/2.4/mave/plugins/bw6-maven-plugin contains the following:
        dtredinnick@ubuntu:/opt/tibco/bwce/bwce/2.4/maven/plugins/bw6-maven-plugin$ ls
        bw6-maven-plugin-2.0.0.jar                   fabric8      pom.xml
        com.tibco.bw.palette.shared_6.1.100.003.jar  install.bat
        com.tibco.xml.cxf.common_1.3.200.001.jar     install.sh

**Comment by HiteshNembhwani** [comment]
@SujataDarekar I'm getting the same issue as well and for now have manually removed the dependency from the pom file. @ashutoshbhide mentioned yesterday he has a fix for this issue, will wait for him.

**Comment by dtredinnick13** [comment]
@SujataDarekar, I don't see the shared jar file.  Instead I see what looks like a jar file with a .lastupdated extension.    Could the solution be as simple as renaming the files to remove the ".lastupdated" extension?  

Here are the contents of the sub-directories under com.tibco.bw.palette.shared:

dtredinnick@ubuntu:~/.m2/repository/com/tibco/plugins$ cd com.tibco.bw.palette.shared/
dtredinnick@ubuntu:~/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared$ ls
6.1.100
dtredinnick@ubuntu:~/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared$ cd 6.1.100/
dtredinnick@ubuntu:~/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100$ ls
com.tibco.bw.palette.shared-6.1.100.jar.lastUpdated  m2e-lastUpdated.properties
com.tibco.bw.palette.shared-6.1.100.pom.lastUpdated

**Comment by SujataDarekar** [comment]
@dtredinnick13  Jar is present with ".lastupdated" extension hence it is showing error while generating the POM file and it is resolved in Maven Plugin 2.0.1 .Could you please try with Maven Plugin 2.0.1?

**Comment by mmussett** [comment]
@ashutoshbhide how quickly can we get a fix for this. We have a customer who's also hit this issue and are unable to run their CI/CD pipeline until this is fixed?

**Comment by SujataDarekar** [comment]
@dtredinnick13 @mmussett As discussed with Ashutosh issue is fixed hence closing the issue

**Comment by HiteshNembhwani** [comment]
@SujataDarekar which version is the issue fixed and is it available for everyone? I have a local copy from @ashutoshbhide but not sure if this is already committed to GH repo.

**Comment by SujataDarekar** [comment]
@HiteshNembhwani  It is fixed with version Maven Plugin 2.0.1 and it is available to everyone.

**Comment by ashutoshbhide** [comment]
@HiteshNembhwani 
This is now fixed with the 2.0.1 version after re-uploading the binaries. 
I had a email conversation with @mmussett  and it is now working for him as well.

We tried it on a freshly created VM and now its working there as well.

Ashutosh

**Comment by tirukommi** [comment]
Hi SujataDarekar,

Request you to please provide a solution here for the above issue as I am facing the same in BW6.5 and maven 2.1.

Thanks ahead !!
----
Tiru

**Comment by saravanaprasaths** [comment]
Hi All,

I am using BWCE 2.3.4 and using Maven plugin 1.3.1. Still getting the below error:

Error: Missing artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100	pom.xml	/HelloWorld.module	line 14	Maven Dependency Problem

I can find the jar file in the below directory:
TIBCO_HOME\bwce\2.3\maven\plugins\bw6-maven-plugin\com.tibco.bw.palette.shared_6.1.100.003.jar

Please help how to resolve?

**Comment by rsunkavalli** [comment]
Hi,
I am facing the same issue with BW 6.4.2 and Maven plugin 1.3.1.
The POM for com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 is missing, no dependency information available
Failed to execute goal on project Application.app.module: Could not resolve dependencies for project com.tibco.bw:Application.app.module:bwmodule:1.0.0-SNAPSHOT: Could not find artifact com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
I checked in .m2\repository\com\tibco\plugins
The com.tibco.plugins:com.tibco.bw.palette.shared:jar:6.1.100 jar file is under com.tibco.bw.palette.shared\6.1.100 folder instead of having it under \bw6-maven-plugin\ folder.
![image](https://user-images.githubusercontent.com/59032803/71124277-20ff9880-21aa-11ea-8611-3465f1a4b0b2.png)
Can someone please help to resolve this isue?

Thanks in advance.
