### ISSUE TITLE
Unable to Build TIBCO BW6.x EAR from Jenkins via Maven.

### ISSUE THREAD

**Issue by rraghu214** [TIBCOSoftware/bw6-plugin-maven#33]
Hi All, I'm able to build an EAR using Maven Plugin from BW Studio. I have installed Maven plugin for Jenkins and trying to achieve the same from Jenkins, but failing as it is unable to recognize 'bwear'. I have attached a detailed report on the issue I'm facing. 

Appreciate your help!

Versions:

TIBCO Business Works 6.3.3
Jenkins 2.7.1, Maven Integration plugin (for Jenkins)- 2.13
TIB_BW_Maven_Plugin_1.1.0
Apache Maven 3.3.9
[JenkinsBuildIssue.docx](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/479148/JenkinsBuildIssue.docx)

**Comment by HiteshNembhwani** [comment]
Raghu,

Under the Jenkins Job configuration, could you specify the parent POM and
give it a try?

(i.e. in your case:
tibco.bw.sample.binding.rest.BookStore.application.parent\pom.xml)

-Hitesh

**Comment by rraghu214** [comment]
![parentpom](https://cloud.githubusercontent.com/assets/15065383/18639865/403b37c4-7eb3-11e6-8660-e15c05592148.JPG)
Hi Hitesh, Thanks for the response. 
Still getting the same error - "Unknown packaging: bwear". I have attached screenshot.
Please share your thoughts. We are very keen to proceed with Jenkins->Maven->BW6!
Many Thanks.

**Comment by fanninj3** [comment]
I'm pretty sure your problem is that you do not have the BW Maven plugin installed in the maven repository being used by Jenkins. Double check this, and install if missing. Then it should work fine.

**Comment by rraghu214** [comment]
![image](https://cloud.githubusercontent.com/assets/15065383/18648164/0c6e14ec-7ed7-11e6-9e2f-36edccb0a8bf.png)

I have a single instance of Maven in my machine and able to locate the JARs in my user repo too
![image](https://cloud.githubusercontent.com/assets/15065383/18648286/9e4a4fca-7ed7-11e6-994e-80f51dc85416.png)


Build from studio works.. not sure if I'm missing anything else while executing from Jenkins.

I also suspect, why would jenkins try to look for the JAR from https://repo.maven.apache.org/maven2, rather than from my local folders!
![image](https://cloud.githubusercontent.com/assets/15065383/18648387/10593298-7ed8-11e6-97b1-0ce4f1101a6c.png)

**Comment by rraghu214** [comment]
Hi Folks, Is there a way to edit Effective POM? Want to point the Maven Plugin Repository to my local path instead of http repository. (I don't know if it is recommended way to handle.. is there any alternate way?).. Have attached my workspace, just in case you want to have a look at the POMs..
![image](https://cloud.githubusercontent.com/assets/15065383/18657526/a79a86b2-7f18-11e6-9964-f8a6584bd1f8.png)


[NewWksp.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/481633/NewWksp.zip)

**Comment by rraghu214** [comment]
Hi All, Thanks much for your support. Atlast found the solution. 👍 :)
Enable following entry in settings.xml present in MAVEN_HOME\conf.
<localRepository><User_HOME>\.m2\repository</localRepository>

Also ensure to use default Maven Repo in Manage Jenkins -> Configure System
![image](https://cloud.githubusercontent.com/assets/15065383/18696780/3cfb1328-7fd9-11e6-9bb5-772406160539.png)

Ideally the following command must be executed by Jenkins for the build to work!
-B -f <workspace>\tibco.bw.sample.binding.rest.BookStore.application.parent\pom.xml -s <MAVEN_HOME>\conf\settings.xml clean package

Have attached Build logs for reference!
[JenkinsBuild.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/484057/JenkinsBuild.txt)

**Comment by venkat1122** [comment]
Thanks Raghu...It is resolved!

**Comment by vinisha91** [comment]
Hi @rraghu214 
I am facing the similar like you did in my linux machine, did everything that you have mentioned but still not able to solve it, i have created it as a issue pls chk and let me know if you can help:
https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/110
