### ISSUE TITLE
BusinessStudio hangs while validating project with Shared Module as a Maven dependency

### ISSUE THREAD

**Issue by richardelowe** [TIBCOSoftware/bw6-plugin-maven#568]
-------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version: 2.8.0

Maven version: 3.3.3 (embedded within Studio)

Product : TIBCO Businessworks Container edition

Product version: 2.6.0 and 2.6.1

Component: Maven Eclipse Plugin

**Steps to reproduce the issue:**
1. Export a BWCE project built in 2.5.4 that imports a Shared Module as a Maven dependency
2. Create a new workspace in 2.6.0 or 2.6.1 and import project from Step 1

**Additional environment details if any:**
Tested on MacOS and RHEL 7.x

**Describe the results you received:**
The workpace appears to pull in the Shared Module but then hangs while building the workspace with the following error:
```
Setting classpath containers: Invoking 'BusinessWorks Project Validation Builder' on 
'<application module name>'
```

**Describe the results you expected:**
Workspace should finish importing the project and then allow user to continue with Design

**Additional information you deem important (e.g. issue happens only occasionally):**

- If the Maven dependency doesn't exist in the local .m2 repository then the Workspace opens fine (but correctly shows an error that there's a missing dependency in the Problems tab)
- I can't reproduce this with simple projects - I've only seen it on more complex projects

**Comment by vpawar-tibco** [comment]
Hi @richardelowe Could you try increasing the studio memory at `<TIBCO-HOME>\studio\4.0\eclipse\TIBCOBusinessStudio.ini`? Please increase the value for `-Xmx` parameter and restart the studio.

**Comment by richardelowe** [comment]
I tried using -Xmx8192m but I'm still getting the issue

**Comment by SujataDarekar** [comment]
@richardelowe The issue is in BW and has been fixed with AMBW-42859. Closing the issue

**Comment by imranswork** [comment]
I am still getting this issue using BW 6.7 and BW_Maven_Plugin_2.8.0, studio hangs with message building workspace
